### ISSUE TITLE
Connection pool with `auto-commit: false` not working

### ISSUE THREAD

**Issue by JakubHave** [coditory/sherlock-distributed-lock#133]
## Context
I am using Sherlock for distributed locking mechanism in mission critical application, which is a SpringBoot 3 with PostgreSQL DB. Due to some performance reasons I would like to setup datasource Hikari connection pool property `auto-commit: false`.
But Sherlock works only when `auto-commit: true`.

My configuration of Sherlock  is as follows:
`sqlSherlock().withConnectionPool(dataSource).withLocksTable("locks")...`

## Expected Behavior
Sherlock works with datasource connection pool property `auto-commit: false`

## Current Behavior
Sherlock works only when `auto-commit: true`.
For `auto-commit: false` it seems that Sherlock can not commit the DB transaction and throws exceptions when it tries to acquire a lock:

com.coditory.sherlock.SherlockException: Could not acquire or prolong lock: LockRequest{lockId=LockId(..., duration=LockDuration(PT1M)}
	at com.coditory.sherlock.SqlDistributedLockConnector.acquireOrProlong(SqlDistributedLockConnector.java:53)
	at com.coditory.sherlock.DelegatingDistributedLock.acquire(DelegatingDistributedLock.java:64)
	at com.coditory.sherlock.DelegatingDistributedLock.acquire(DelegatingDistributedLock.java:38)

java.lang.IllegalStateException: Could not initialize locks table
	at com.coditory.sherlock.SqlTableInitializer.initialize(SqlTableInitializer.java:39)
	at com.coditory.sherlock.SqlTableInitializer.getInitializedStatement(SqlTableInitializer.java:18)
	at com.coditory.sherlock.SqlDistributedLockConnector.getStatement(SqlDistributedLockConnector.java:190)
	at com.coditory.sherlock.SqlDistributedLockConnector.updateAcquiredOrReleasedLock(SqlDistributedLockConnector.java:84)
	at com.coditory.sherlock.SqlDistributedLockConnector.acquireOrProlong(SqlDistributedLockConnector.java:50)

org.postgresql.util.PSQLException: ERROR: relation "locks" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)

**Comment by sureshg** [comment]
Sad to see this issue getting closed...it would be great if sherlock can work with `auto-commit: false`

**Comment by JakubHave** [comment]
@sureshg the only workaround I could think of would be to setup a second Datasource with `auto-commit: true` just for Sherlock and have the primary Datasource used by Spring/Hibernate for business logic with `auto-commit: false`.
But having 2 Datasources is also not ideal...

**Comment by sureshg** [comment]
> @sureshg the only workaround I could think of would be to setup a second Datasource with `auto-commit: true` just for Sherlock and have the primary Datasource used by Spring/Hibernate for business logic with `auto-commit: false`.
> But having 2 Datasources is also not ideal...
> 

Thanks for the reply... exactly this is what I am doing right now ...creating another data source with a smaller pool for Sherlock.
