### ISSUE TITLE
Java 11 Support

### ISSUE THREAD

**Issue by driseley** [coditory/sherlock-distributed-lock#89]
I am trying to run Sherlock under Java 11 - is this still supported?  It looks like it has been compiled for Java 17:

```
Caused by: java.lang.UnsupportedClassVersionError: com/coditory/sherlock/Sherlock has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[na:na]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800) ~[na:na]
```

**Comment by driseley** [comment]
I have added PR#90 as a proposed fix for this

**Comment by ogesaku** [comment]
@driseley I can see that there is a problem on master. Java 11 is conflicting with another plugin.
We will solve it today in a spare moment. You can expect a new release tomorrow.

**Comment by ogesaku** [comment]
@driseley Ok, master with java 11 support is fixed. Please try version `0.4.18`.

**Comment by driseley** [comment]
@ogesaku - Many thanks for that `0.4.18` works great for us.  Will close this.
